apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: nginx-dr
  namespace: nginx-rollout
spec:
  host: nginx-stable
  subsets:
    - name: stable
      labels:
        app: nginx
    - name: canary
      labels:
        app: nginx
