apiVersion: v1
kind: Namespace
metadata:
  name: nginx-rollout
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-stable
  namespace: nginx-rollout
spec:
  type: LoadBalancer
  selector:
    app: nginx-rollout
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-canary
  namespace: nginx-rollout
spec:
  type: LoadBalancer
  selector:
    app: nginx-rollout
  ports:
    - port: 80
      targetPort: 80
