apiVersion: v1
kind: Namespace
metadata:
  name: nginx-rollout
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-stable
  namespace: nginx-rollout
spec:
  externalIPs: 
    - 10.0.0.160
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-canary
  namespace: nginx-rollout
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
