apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-vs
  namespace: nginx-rollout
spec:
  hosts:
    - politicas.kdvops.com
  gateways:
    - istio-system/kdvops-gateway
  http:
    - name: primary
      route:
        - destination:
            host: nginx-stable
            subset: stable
          weight: 100
        - destination:
            host: nginx-stable
            subset: canary
          weight: 0
