apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-vs
  namespace: nginx-rollout
spec:
  hosts:
    - politicas2.kdvops.com
  gateways:
    - istio-system/kdvops-gateway
  http:
    - name: primary
      route:
        - destination:
            host: nginx-stable
            subset: stable
          weight: 100
        - destination:
            host: nginx-stable
            subset: canary
          weight: 0
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-vs2
  namespace: nginx-rollout
  annotations:
    external-dns.alpha.kubernetes.io/hostname: politicas.kdvops.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  hosts:
  - "politicas.kdvops.com"
  gateways:
  - istio-system/kdvops-gateway
  http:
  - route:
    - destination:
        host: nginx-stable
        port:
          number: 80
